name: semicolons
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.21
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  # flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_gemini: ^2.0.4
  flutter_tts: ^3.8.0
  get: ^4.6.6
  just_audio: ^0.9.37
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  speech_to_text: ^6.6.1
  url_launcher: ^6.2.6
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/0/
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
